export const CARD_TYPES = {
  ATTACK: 'attack',
  DEFENSE: 'defense',
  SKILL: 'skill',
  CONTROL: 'control',
  POWER: 'power',
  KILLER_MOVE: 'killerMove',
  FORMATION: 'formation',
};

export const DECK_LIMITS = {
  recommended: 30,
  max: 50,
};

export const CARD_PATHS = {
  BASIC: 'basic',
  FIRE: 'fire',
  POISON: 'poison',
  EARTH: 'earth',
  METAL: 'metal',
  WOOD: 'wood',
  WATER: 'water',
  WIND: 'wind',
  SWORD: 'sword',
  STRENGTH: 'strength',
  BONE: 'bone',
  BLOOD: 'blood',
  DARK: 'dark',
  CLOUD: 'cloud',
  WISDOM: 'wisdom',
  LIGHTNING: 'lightning',
  ICE: 'ice',
  FORMATION: 'formation',
};

export const INTENT_TYPES = {
  ATTACK: 'attack',
  DEFEND: 'defend',
  SKILL: 'skill',
  DEBUFF: 'debuff',
  HEAL: 'heal',
  BUFF: 'buff',
  PREPARE: 'prepare',
  UNKNOWN: 'unknown',
};

export const INTENT_DEFS = {
  attack: {
    icon: '⚔',
    key: 'card.intent.attack',
    summaryKey: 'card.intent.attack.summary',
    tooltipKey: 'card.intent.attack.tip',
    damage: 10,
  },
  defend: {
    icon: '🛡',
    key: 'card.intent.defend',
    summaryKey: 'card.intent.defend.summary',
    tooltipKey: 'card.intent.defend.tip',
    armor: 12,
  },
  skill: {
    icon: '✦',
    key: 'card.intent.skill',
    summaryKey: 'card.intent.skill.summary',
    tooltipKey: 'card.intent.skill.tip',
    applies: 'poison',
  },
  debuff: {
    icon: '☠',
    key: 'card.intent.debuff',
    summaryKey: 'card.intent.debuff.summary',
    tooltipKey: 'card.intent.debuff.tip',
    applies: 'poison',
  },
  heal: {
    icon: '✚',
    key: 'card.intent.heal',
    summaryKey: 'card.intent.heal.summary',
    tooltipKey: 'card.intent.heal.tip',
    heal: 8,
  },
  buff: {
    icon: '▲',
    key: 'card.intent.buff',
    summaryKey: 'card.intent.buff.summary',
    tooltipKey: 'card.intent.buff.tip',
    applies: 'fortify',
  },
  prepare: {
    icon: '◆',
    key: 'card.intent.prepare',
    summaryKey: 'card.intent.prepare.summary',
    tooltipKey: 'card.intent.prepare.tip',
    damage: 21,
    damageRange: [18, 24],
  },
  unknown: {
    icon: '?',
    key: 'card.intent.unknown',
    summaryKey: 'card.intent.unknown.summary',
    tooltipKey: 'card.intent.unknown.tip',
    hidden: true,
  },
};

export const STATUS_DEFS = {
  scorch: {
    key: 'card.status.scorch',
    tooltipKey: 'card.status.scorch.tip',
    stackable: true,
    consumed: true,
    decay: 'minusOneEndTurn',
  },
  poison: {
    key: 'card.status.poison',
    tooltipKey: 'card.status.poison.tip',
    stackable: true,
    trigger: 'end',
    cap: 12,
    decay: 'halveEndTurn',
  },
  fortify: {
    key: 'card.status.fortify',
    tooltipKey: 'card.status.fortify.tip',
    stackable: true,
  },
  thorns: {
    key: 'card.status.thorns',
    tooltipKey: 'card.status.thorns.tip',
    stackable: true,
  },
  cloudVeil: {
    key: 'card.status.cloudVeil',
    tooltipKey: 'card.status.cloudVeil.tip',
    stackable: false,
    consumed: true,
  },
  skillSeal: {
    key: 'card.status.skillSeal',
    tooltipKey: 'card.status.skillSeal.tip',
    stackable: false,
    duration: 1,
  },
  bloodFury: {
    key: 'card.status.bloodFury',
    tooltipKey: 'card.status.bloodFury.tip',
    stackable: true,
    permanent: true,
  },
  swordIntent: {
    key: 'card.status.swordIntent',
    tooltipKey: 'card.status.swordIntent.tip',
    stackable: true,
    consumed: true,
  },
  regeneration: {
    key: 'card.status.regeneration',
    tooltipKey: 'card.status.regeneration.tip',
    stackable: true,
    trigger: 'start',
  },
  windChain: {
    key: 'card.status.windChain',
    tooltipKey: 'card.status.windChain.tip',
    stackable: false,
    consumed: true,
  },
  frost: {
    key: 'card.status.frost',
    tooltipKey: 'card.status.frost.tip',
    stackable: true,
    duration: 1,
  },
};

export const PATH_IDENTITIES = [
  { path: CARD_PATHS.FIRE, primary: 'card.path.fire.primary', secondary: 'card.path.fire.secondary', weakness: 'card.path.fire.weakness' },
  { path: CARD_PATHS.POISON, primary: 'card.path.poison.primary', secondary: 'card.path.poison.secondary', weakness: 'card.path.poison.weakness' },
  { path: CARD_PATHS.EARTH, primary: 'card.path.earth.primary', secondary: 'card.path.earth.secondary', weakness: 'card.path.earth.weakness' },
  { path: CARD_PATHS.METAL, primary: 'card.path.metal.primary', secondary: 'card.path.metal.secondary', weakness: 'card.path.metal.weakness' },
  { path: CARD_PATHS.WOOD, primary: 'card.path.wood.primary', secondary: 'card.path.wood.secondary', weakness: 'card.path.wood.weakness' },
  { path: CARD_PATHS.WATER, primary: 'card.path.water.primary', secondary: 'card.path.water.secondary', weakness: 'card.path.water.weakness' },
  { path: CARD_PATHS.WIND, primary: 'card.path.wind.primary', secondary: 'card.path.wind.secondary', weakness: 'card.path.wind.weakness' },
  { path: CARD_PATHS.SWORD, primary: 'card.path.sword.primary', secondary: 'card.path.sword.secondary', weakness: 'card.path.sword.weakness' },
  { path: CARD_PATHS.STRENGTH, primary: 'card.path.strength.primary', secondary: 'card.path.strength.secondary', weakness: 'card.path.strength.weakness' },
  { path: CARD_PATHS.BONE, primary: 'card.path.bone.primary', secondary: 'card.path.bone.secondary', weakness: 'card.path.bone.weakness' },
  { path: CARD_PATHS.BLOOD, primary: 'card.path.blood.primary', secondary: 'card.path.blood.secondary', weakness: 'card.path.blood.weakness' },
  { path: CARD_PATHS.DARK, primary: 'card.path.dark.primary', secondary: 'card.path.dark.secondary', weakness: 'card.path.dark.weakness' },
  { path: CARD_PATHS.CLOUD, primary: 'card.path.cloud.primary', secondary: 'card.path.cloud.secondary', weakness: 'card.path.cloud.weakness' },
  { path: CARD_PATHS.WISDOM, primary: 'card.path.wisdom.primary', secondary: 'card.path.wisdom.secondary', weakness: 'card.path.wisdom.weakness' },
  { path: CARD_PATHS.LIGHTNING, primary: 'card.path.lightning.primary', secondary: 'card.path.lightning.secondary', weakness: 'card.path.lightning.weakness' },
  { path: CARD_PATHS.ICE, primary: 'card.path.ice.primary', secondary: 'card.path.ice.secondary', weakness: 'card.path.ice.weakness' },
  { path: CARD_PATHS.FORMATION, primary: 'card.path.formation.primary', secondary: 'card.path.formation.secondary', weakness: 'card.path.formation.weakness' },
];

export const STARTER_CARDS = [
  {
    id: 'strike',
    key: 'card.basic.strike',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.BASIC,
    apCost: 1,
    essenceCost: 0,
    damage: [3, 6],
    descriptionKey: 'card.basic.strike.desc',
    count: 4,
  },
  {
    id: 'guard',
    key: 'card.basic.guard',
    type: CARD_TYPES.DEFENSE,
    path: CARD_PATHS.BASIC,
    apCost: 1,
    essenceCost: 0,
    armor: 6,
    descriptionKey: 'card.basic.guard.desc',
    count: 3,
  },
  {
    id: 'focusBreath',
    key: 'card.basic.focusBreath',
    type: CARD_TYPES.SKILL,
    path: CARD_PATHS.BASIC,
    apCost: 1,
    essenceCost: 0,
    essenceRecover: 2,
    descriptionKey: 'card.basic.focusBreath.desc',
    count: 2,
  },
];

export const GU_CARDS = [
  {
    id: 'swiftFangGu',
    key: 'card.gu.swiftFang',
    guId: 'swiftFangGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.WIND,
    apCost: 1,
    essenceCost: 3,
    damage: [6, 9],
    draw: 1,
    applySelfStatus: [{ id: 'windChain', stacks: 1, duration: 1 }],
    descriptionKey: 'card.gu.swiftFang.desc',
  },
  {
    id: 'stoneShellGu',
    key: 'card.gu.stoneShell',
    guId: 'stoneShellGu',
    type: CARD_TYPES.DEFENSE,
    path: CARD_PATHS.EARTH,
    apCost: 1,
    essenceCost: 4,
    armor: 10,
    applySelfStatus: [{ id: 'fortify', stacks: 1, duration: 3 }],
    descriptionKey: 'card.gu.stoneShell.desc',
  },
  {
    id: 'emberFangGu',
    key: 'card.gu.emberFang',
    guId: 'emberFangGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.FIRE,
    apCost: 1,
    essenceCost: 4,
    damage: [8, 11],
    applyTargetStatus: [{ id: 'scorch', stacks: 2 }],
    descriptionKey: 'card.gu.emberFang.desc',
  },
  {
    id: 'poisonNeedleGu',
    key: 'card.gu.poisonNeedle',
    guId: 'poisonNeedleGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.POISON,
    apCost: 1,
    essenceCost: 3,
    damage: [4, 7],
    applyTargetStatus: [{ id: 'poison', stacks: 6 }],
    descriptionKey: 'card.gu.poisonNeedle.desc',
  },
  {
    id: 'waterFlowGu',
    key: 'card.gu.waterFlow',
    guId: 'waterFlowGu',
    type: CARD_TYPES.SKILL,
    path: CARD_PATHS.WATER,
    apCost: 1,
    essenceCost: 2,
    essenceRecover: 4,
    essenceDiscount: 2,
    descriptionKey: 'card.gu.waterFlow.desc',
  },
  {
    id: 'boneThornGu',
    key: 'card.gu.boneThorn',
    guId: 'boneThornGu',
    type: CARD_TYPES.DEFENSE,
    path: CARD_PATHS.BONE,
    apCost: 1,
    essenceCost: 4,
    armor: 4,
    applySelfStatus: [{ id: 'thorns', stacks: 3, duration: 3 }],
    descriptionKey: 'card.gu.boneThorn.desc',
  },
  {
    id: 'wisdomThreadGu',
    key: 'card.gu.wisdomThread',
    guId: 'wisdomThreadGu',
    type: CARD_TYPES.SKILL,
    path: CARD_PATHS.WISDOM,
    apCost: 1,
    essenceCost: 3,
    retrieveFromDiscard: 1,
    keywords: ['search'],
    descriptionKey: 'card.gu.wisdomThread.desc',
  },
  {
    id: 'cloudVeilGu',
    key: 'card.gu.cloudVeil',
    guId: 'cloudVeilGu',
    type: CARD_TYPES.DEFENSE,
    path: CARD_PATHS.CLOUD,
    apCost: 1,
    essenceCost: 5,
    applySelfStatus: [{ id: 'cloudVeil', stacks: 1, duration: 1 }],
    keywords: ['retain'],
    descriptionKey: 'card.gu.cloudVeil.desc',
  },
  {
    id: 'darkSealGu',
    key: 'card.gu.darkSeal',
    guId: 'darkSealGu',
    type: CARD_TYPES.CONTROL,
    path: CARD_PATHS.DARK,
    apCost: 1,
    essenceCost: 5,
    applyTargetStatus: [{ id: 'skillSeal', stacks: 1, duration: 1 }],
    descriptionKey: 'card.gu.darkSeal.desc',
  },
  {
    id: 'ironPierceGu',
    key: 'card.gu.ironPierce',
    guId: 'ironPierceGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.METAL,
    apCost: 1,
    essenceCost: 3,
    damage: [5, 8],
    pierce: 0.5,
    armorBreak: 1,
    descriptionKey: 'card.gu.ironPierce.desc',
  },
  {
    id: 'woodMendGu',
    key: 'card.gu.woodMend',
    guId: 'woodMendGu',
    type: CARD_TYPES.SKILL,
    path: CARD_PATHS.WOOD,
    apCost: 1,
    essenceCost: 3,
    heal: 5,
    applySelfStatus: [{ id: 'regeneration', stacks: 2, duration: 3 }],
    descriptionKey: 'card.gu.woodMend.desc',
  },
  {
    id: 'bloodRendGu',
    key: 'card.gu.bloodRend',
    guId: 'bloodRendGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.BLOOD,
    apCost: 1,
    essenceCost: 2,
    hpCost: 5,
    damage: [13, 17],
    descriptionKey: 'card.gu.bloodRend.desc',
  },
  {
    id: 'bloodLeechGu',
    key: 'card.gu.bloodLeech',
    guId: 'bloodLeechGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.BLOOD,
    apCost: 1,
    essenceCost: 3,
    damage: [6, 9],
    lifesteal: 0.4,
    descriptionKey: 'card.gu.bloodLeech.desc',
  },
  {
    id: 'bloodFuryGu',
    key: 'card.gu.bloodFury',
    guId: 'bloodFuryGu',
    type: CARD_TYPES.POWER,
    path: CARD_PATHS.BLOOD,
    apCost: 1,
    essenceCost: 4,
    hpCost: 6,
    applySelfStatus: [{ id: 'bloodFury', stacks: 1, permanent: true }],
    keywords: ['exhaust'],
    descriptionKey: 'card.gu.bloodFury.desc',
  },
  {
    id: 'thunderPalmGu',
    key: 'card.gu.thunderPalm',
    guId: 'thunderPalmGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.LIGHTNING,
    apCost: 1,
    essenceCost: 4,
    damage: [7, 10],
    descriptionKey: 'card.gu.thunderPalm.desc',
  },
  {
    id: 'frostNeedleGu',
    key: 'card.gu.frostNeedle',
    guId: 'frostNeedleGu',
    type: CARD_TYPES.CONTROL,
    path: CARD_PATHS.ICE,
    apCost: 1,
    essenceCost: 4,
    damage: [3, 5],
    applyTargetStatus: [{ id: 'frost', stacks: 1, duration: 1 }],
    descriptionKey: 'card.gu.frostNeedle.desc',
  },
  {
    id: 'galeBladeGu',
    key: 'card.gu.galeBlade',
    guId: 'galeBladeGu',
    type: CARD_TYPES.ATTACK,
    path: CARD_PATHS.WIND,
    apCost: 1,
    essenceCost: 4,
    damage: [7, 10],
    applySelfStatus: [{ id: 'windChain', stacks: 1, duration: 1 }],
    descriptionKey: 'card.gu.galeBlade.desc',
  },
];

export const KILLER_MOVE_CARDS = [
  {
    id: 'thunderGaleFang',
    key: 'card.km.thunderGaleFang',
    type: CARD_TYPES.KILLER_MOVE,
    path: CARD_PATHS.WIND,
    apCost: 2,
    essenceCost: 14,
    damage: [22, 30],
    requiredGu: ['swiftFangGu', 'thunderPalmGu', 'galeBladeGu'],
    boundGu: ['swiftFangGu', 'thunderPalmGu', 'galeBladeGu'],
    applySelfStatus: [{ id: 'windChain', stacks: 1, duration: 1 }],
    keywords: ['exhaust'],
    descriptionKey: 'card.km.thunderGaleFang.desc',
  },
  {
    id: 'emberRainFormation',
    key: 'card.km.emberRainFormation',
    type: CARD_TYPES.KILLER_MOVE,
    path: CARD_PATHS.FIRE,
    apCost: 2,
    essenceCost: 12,
    damage: [10, 14],
    targetMode: 'all',
    requiredGu: ['emberFangGu', 'stoneShellGu'],
    boundGu: ['emberFangGu', 'stoneShellGu'],
    applyTargetStatus: [{ id: 'scorch', stacks: 2 }],
    keywords: ['exhaust'],
    descriptionKey: 'card.km.emberRainFormation.desc',
  },
];

export const SAMPLE_RELICS = [
  {
    id: 'emberHeartPendant',
    key: 'card.relic.emberHeartPendant',
    modifier: { path: CARD_PATHS.FIRE, damageBelowHalfPct: 0.1 },
    descriptionKey: 'card.relic.emberHeartPendant.desc',
  },
  {
    id: 'crackedBoneMirror',
    key: 'card.relic.crackedBoneMirror',
    modifier: { thornsBonus: 2 },
    descriptionKey: 'card.relic.crackedBoneMirror.desc',
  },
  {
    id: 'cloudstepToken',
    key: 'card.relic.cloudstepToken',
    modifier: { firstWindApFree: true },
    descriptionKey: 'card.relic.cloudstepToken.desc',
  },
];

export const SAMPLE_LOADOUT = {
  equippedGu: GU_CARDS.map((card) => card.guId),
  equippedKillerMoves: ['thunderGaleFang'],
  starterCounts: Object.fromEntries(STARTER_CARDS.map((card) => [card.id, card.count || 1])),
  relics: ['emberHeartPendant', 'crackedBoneMirror', 'cloudstepToken'],
};

export const CARD_COLLECTION = {
  starter: STARTER_CARDS,
  gu: GU_CARDS,
  killerMoves: KILLER_MOVE_CARDS,
  relics: SAMPLE_RELICS,
};

export const ENCOUNTERS = {
  single: {
    key: 'card.encounter.single',
    waves: [[
      { id: 'jadeBandit', key: 'card.enemy.jadeBandit', maxHp: 48, hp: 48, armor: 0, intents: ['attack', 'defend', 'skill'] },
    ]],
  },
  multi: {
    key: 'card.encounter.multi',
    waves: [[
      { id: 'ashenCultivator', key: 'card.enemy.ashenCultivator', maxHp: 34, hp: 34, armor: 0, intents: ['skill', 'attack'] },
      { id: 'ironGuard', key: 'card.enemy.ironGuard', maxHp: 42, hp: 42, armor: 6, intents: ['defend', 'attack'] },
      { id: 'venomAcolyte', key: 'card.enemy.venomAcolyte', maxHp: 30, hp: 30, armor: 0, intents: ['debuff', 'heal', 'attack'] },
    ]],
  },
  waves: {
    key: 'card.encounter.waves',
    waves: [
      [
        { id: 'wolfBanditA', key: 'card.enemy.wolfBandit', maxHp: 24, hp: 24, armor: 0, intents: ['attack'] },
        { id: 'wolfBanditB', key: 'card.enemy.wolfBandit', maxHp: 24, hp: 24, armor: 0, intents: ['attack'] },
      ],
      [
        { id: 'mistElder', key: 'card.enemy.mistElder', maxHp: 72, hp: 72, armor: 4, intents: ['skill', 'prepare', 'buff', 'attack'] },
      ],
    ],
  },
  elite: {
    key: 'card.encounter.elite',
    waves: [[
      { id: 'obsidianDaoist', key: 'card.enemy.obsidianDaoist', maxHp: 96, hp: 96, armor: 8, intents: ['prepare', 'unknown', 'skill', 'attack', 'defend'] },
    ]],
  },
};
